//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMAPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int id { get; set; }
        public int catid { get; set; }
        public string ProdName { get; set; }
        public decimal Price { get; set; }
        public string ProdDesc { get; set; }
        public string catName { get; set; }
    
        public virtual CatagoryMaster CatagoryMaster { get; set; }
    }
}
